### ISSUE TITLE
 Truncation strategies and evaluation codes

### ISSUE THREAD

**Issue by Mooler0410** [Hambaobao/Marathon#1]
Hi!

Impressive work! I'm trying to use your benchmark to test some open sourced models. However, I encountered two problems:

1: What truncation strategies are used in the paper for open-source models? For example, Qwen has a context window of 8k, if I give a input of 32768, how should I truncate the input to 8k? 

2: Evaluation codes / How to extract the answers? Could you please shares codes for this parts? Should I try to match a json and only keep the first matched json and try to get the answer from that json? 

Thanks!

**Comment by Hambaobao** [comment]
Hi Mooler, thank you for your interest in our work. Below are the replies to your questions:
> What truncation strategies are used in the paper for open-source models? For example, Qwen has a context window of 8k, if I give an input of 32768, how should I truncate the input to 8k?

For models evaluated using the Vanilla method, we adopt the same strategy as [Longbench](https://github.com/THUDM/LongBench), controlling the length of the input sequence within the context window range of the model to be evaluated by deleting the content in the middle of the long context.
Here is the code snippet:
```python
max_length = tokenizer.model_max_length - max_new_tokens
tokenized_prompt = tokenizer(prompt, truncation=False, return_tensors="pt").input_ids[0]
length = len(tokenized_prompt)
if len(tokenized_prompt) > tokenizer.model_max_length - max_new_tokens:
    half = max_length // 2
    prompt = tokenizer.decode(tokenized_prompt[:half], skip_special_tokens=True) \
        + tokenizer.decode(tokenized_prompt[-half:], skip_special_tokens=True)
```
---

> Evaluation codes / How to extract the answers? Could you please shares codes for this parts? Should I try to match a json and only keep the first matched json and try to get the answer from that json?

If you used a prompt similar to ours, you could use regular expressions to extract the answer from the model's output in JSON format, like this:
```python
if d['answer'] not in ['A', 'B', 'C', 'D']:
    flag = False

    if d['reason'] in ['A', 'B', 'C', 'D']:
        d['answer'] = d['reason']
        flag = True

    if not flag:
        try:
            matches = re.findall(r'"?o?p?t?i?o?n?"?\s*:?\s*["\']\s*([ABCD])\s*["\']', d['reason'])

            d['answer'] = matches[0]
            if d['answer'] in ['A', 'B', 'C', 'D']:
                flag = True
        except:
            pass

    if not flag:
        try:
            matches = re.findall(r'"?o?p?t?i?o?n?"?\s*:?\s*["\']\s*([ABCD]).\s*', d['reason'])

            d['answer'] = matches[0]
            if d['answer'] in ['A', 'B', 'C', 'D']:
                flag = True
        except:
            pass
```

The specific rules might need to be adjusted for different models, but if the model you are evaluating has good instruction-following capabilities, using such regular expressions for extraction should suffice.

We will provide an example of `generate.py` later  and update the `README.md`.

**Comment by Mooler0410** [comment]
Thank you for the quick response, really appreciate it! Will have a try.

**Comment by htsplex** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
IISmichinaboy, @huaq-dd, @mingzidouzhemenanqi, @QiiiLi, @zmh93, @littlexzt, @zhyj3038, @comerss, @leonboxer, @hh11813, @ugvfpdcuwfnh, @RiverMud, @Ox0400, @DankeGott, @Cainrin, @forwardxxx, @zira-wang, @wupingyan, @Chen-Xintong, @zqbenyip, @progcxw, @nobodyin1111, @happyday258, @hillmychen, @NutshellySima, @nickchef, @zhchenyang, @zouguo-eng, @qiri07, @ChenXiyu, @bm3ng, @pinweichen, @hds22, @sunker0115, @theshdowaura, @Ansel-Yang0, @ruipengliu, @leojj418, @ZachariahQi, @megonx, @AllenLi1973, @wlkao117, @MuYunyun, @jiazengzeng, @nevergreen, @xbeian, @paradiseHIT, @lym008, @arvinrh, @lguoca
